# Generated by Django 5.2.10 on 2026-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Biceps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Forearms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shoulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Triceps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('set_1', models.CharField(default=0, max_length=20)),
                ('set_2', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
