# Generated by Django 5.2.10 on 2026-08-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_abs_back_biceps_chest_forearms_leg_shoulder_triceps'),
    ]

    operations = [
        migrations.AddField(
            model_name='abs',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='back',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biceps',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chest',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forearms',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoulder',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triceps',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
