# Generated by Django 5.2.10 on 2026-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_abs_exercise_back_exercise_biceps_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='exercise',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
