# Generated by Django 5.2.10 on 2026-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0004_leg_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default='2026-08-30'),
            preserve_default=False,
        ),
    ]
