# Generated by Django 5.2.10 on 2026-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0005_user_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='Null', upload_to=''),
            preserve_default=False,
        ),
    ]
